# Main settings
base_url = "https://mthehorrible.cc"
title = "MtheHorrible"
description = "Bits of Randomness"
default_language = "en"
theme = "simplify"

# Build settings
compile_sass = false
build_search_index = false
minify_html = false
generate_feed = true

# Taxonomy settings
taxonomies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true }
]

# Markdown settings
[markdown]
highlight_code = true
highlight_theme = "agola-dark"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[extra]
# Navbar
menu = [
    { name = "Home", url = "/" },
    { name = "Notes", url = "/notes/" },
    { name = "Tags", url = "/tags/" },
    { name = "Categories", url = "/categories/" },
    { name = "Feed", url = "/atom.xml" }
]
# Avatar at homepage
avatar_url = "/img/m-green-no-border.png"
# Footer credit
footer_credit = true
# KaTex support
math = false
